### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by cornelius** [Open-Source-Compliance/outbound-oss#1]
We need to choose a license for the content in this repository.

To be compatible with [other material produced by the TODO group](https://todogroup.org/guides/), it would probably be most straight-forward to use CC-BY-SA.

**Comment by OliverFendt** [comment]
I am fine with CC-BY-SA. Are they using 4.0?

**Comment by cornelius** [comment]
Yes, it's [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by OliverFendt** [comment]
License added
