### ISSUE TITLE
Open source metrics and analytics

### ISSUE THREAD

**Issue by misappi** [Open-Source-Compliance/outbound-oss#25]
Write a chapter about open source metrics and analytics in the "starting an OSS project" part.

**Comment by anajsana** [comment]
FYI @misappi I've MR'ed the pull request and added the metrics section at releasing os projects as a new PR 👍

**Comment by misappi** [comment]
@anajsana: Did you merge my PR #28 as well? Just asking since the current structure looks quite different from the structure proposed in that PR.

**Comment by cornelius** [comment]
Added in #30
